config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations", sessions: "users/sessions"} do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :users do
      member do
        get :methode_check
      end
    end
  end
  resources :dashboard do
    collection do
      get :conf
      post :meeting_create
    end
    member do
      get :meeting_delete
    end
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
before_action :authenticate_admin!


  def authenticate_admin!
    authenticate_or_request_with_http_basic('Authentification') do |username, password|
      username == 'besunshine' && password == 'test'
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.all.sort_by{ |m| m.email.downcase }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to admin_users_path
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params_user)
      redirect_to admin_users_path
    else
      render action: :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def methode_check
    @user = User.find(params[:id])
    if @user.update_attributes(activated: !@user.activated)
      redirect_to admin_users_path
    else
      render action: :new
    end
  end

  private

  def params_user
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end

  protected

  def require_login
    unless current_user
      flash[:notice] = "Pour accéder à cette page vous devez être connecté"
      redirect_to root_path
    end
  end

  def check
    if current_user.activated == false
      flash[:alert] = "votre compte a été suspendu, contactez notre service pour avoir plus de détail"
      redirect_to root_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def conf
    @zoom_client = Zoom.new
    @user_id = @zoom_client.user_list['users'][0]['id']
    @meeting_list = @zoom_client.meeting_list(user_id: @user_id)
    puts @meeting_list
  end

  def meeting_create
  end

  def show
    @zoom_client = Zoom.new
    @user_id = @zoom_client.user_list['users'][0]['id']

    @zoom_client.meeting_create(user_id: @user_id)
    respond_to do |format|
      begin
        flash[:success] = 'Votre réunion Zoom a bien été créée'
        format.html { redirect_to conf_dashboard_index_path }
      rescue Zoom::Error => exception
        flash[:alert] = 'Une erreur est survenue, veillez contactez l\'administrateur'
        format.html { redirect_to conf_dashboard_index_path }
      end
    end
  end

  def meeting_delete
    @zoom_client = Zoom.new
    @zoom_client.meeting_delete(meeting_id: params[:id])
    respond_to do |format|
      begin
        flash[:info] = 'Votre réunion Zoom a bien été supprimée'
        format.html { redirect_to conf_dashboard_index_path }
      rescue Zoom::Error => exception
        flash[:alert] = 'Une erreur est survenue, veillez contactez l\'administrateur'
        format.html { redirect_to conf_dashboard_index_path }
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to root_path
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.haml
.container.admin
  = simple_form_for @user, url: admin_user_path(params[:id]) , method: :post do |f|
    .text-left
      %h1 Modifier un Client
      %br
      = f.button :submit, :value => "Valider", class: "menu-button"
      &nbsp;&nbsp;
      ou
      &nbsp;
      = link_to "Retour", :back, class: "back"
      %br/
      %br/
      = f.input :email, label: "Email :"
      = f.input :password, label: "Mots de passe :"

app/views/admin/users/index.html.haml
.container
  .text-left
    %h1 Liste de Clients
    %br/
    = link_to(new_admin_user_path) do
      %button.btn.btn-success
        Ajouter un Client
    %br
    %br
    %table.table.table-striped
      %tr
        %td #
        %td E-mail
        %td.text-center Modifier
        %td.text-center Désactiver/Activer
      - @users.each do |nb|
        %tr
          %td
            = nb.id
          %td
            = nb.email
          %td.text-center
            = link_to (edit_admin_user_path(nb.id)) do
              %i.fas.fa-pen-square.fa-3x
          %td.text-center
            - if nb.activated == true
              = link_to(methode_check_admin_user_path(nb.id)) do
                .fas.fa-check.color-v.fa-3x
            - else
              = link_to(methode_check_admin_user_path(nb.id)) do
                .fas.fa-user-times.color-r.fa-3x

app/views/admin/users/new.html.haml
.container.admin
  = simple_form_for @user, url: admin_users_path , method: :post do |f|
    .text-left
      %h1 Ajouter un client
      %br
      = f.button :submit, :value => "Valider", class: "menu-button"
      &nbsp;&nbsp;
      ou
      &nbsp;
      = link_to "Retour", :back, class: "back"
      %br/
      %br/
      = f.input :email, label: "Email :", autofocus: true
      = f.input :password, label: "Mots de passe :"

app/views/dashboard/conf.html.haml
.container
  .text-left
    %h1 Conf

.container
  = link_to(meeting_create_dashboard_index_path, title: "Zoom", class: "navbar-brand") do
    %button.btn.btn-success Créer une Réunion
  %br
  %br
  .infinite-table.text-left
    %table.table.table-striped
      %tr
        %td Id
        %td Heure de Début
        %td Durée de la Réunion
        %td Rejoindre
        %td Supprimer

      - @meeting_list['meetings'].each do |meeting|
        %tr
          %td
            = meeting['id']
          %td
            = meeting['start_time'].to_datetime.strftime("%d/%m/%Y %Hh%Mmin%Ss")
          %td
            = meeting['duration']
          %td
            = link_to("#{meeting['join_url']}", title: "Zoom", target: "_blank", class: "navbar-brand") do
              %button.btn.btn-primary Rejoindre
          %td
            = link_to(meeting_delete_dashboard_path(meeting['id']), title: "Delete Zoom", class: "navbar-brand") do
              %button.btn.btn-danger Supprimer
      - end.empty? and begin
        %tr
          %td{colspan: "5"}
            .text-center
              Veuillez créer une réunion pour affichez les réunions en cours

app/views/dashboard/index.html.haml
.container
  .text-left
    %h1 Actu


.container
  .text-center
    %iframe{:allow => "autoplay; encrypted-media", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/videoseries?list=PL8apk9p4xESvCTTOYYt_IRhZ4udBhXEmu", :width => "560"}
    %br
    %br
    %iframe{:allow => "autoplay; encrypted-media", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/videoseries?list=PL8apk9p4xESvCTTOYYt_IRhZ4udBhXEmu&index=1", :width => "560"}
    %br
    %br
    %iframe{:allow => "autoplay; encrypted-media", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/videoseries?list=PL8apk9p4xESvCTTOYYt_IRhZ4udBhXEmu&index=2", :width => "560"}

app/views/layouts/_header.html.haml
- if user_signed_in?
  %nav.navbar.navbar-expand-md.navbar-light.bg-light
    = link_to('/dashboard', title: "Actu", class: "navbar-brand") do
      %i.fas.fa-ad.fa-2x
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item{:class => current_page?(dashboard_index_path) && 'active'}
          = link_to 'Actu', dashboard_index_path, title: "Actu", class: "nav-link"
        %li.nav-item{ :class => current_page?(conf_dashboard_index_path) && 'active'}
          = link_to 'Conf', conf_dashboard_index_path, title: "Conf", class: "nav-link"
      %span.navbar-text
        %a{class: "dropdown-header", "aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          %h4
            = current_user.email
        %ul.dropdown-menu
          %li
            = link_to "Mes informations", edit_user_registration_path
          %li.divider{:role => "separator"}
          %li
            = link_to "Déconnexion", destroy_user_session_path, method: :delete

- else
  %nav.navbar.navbar-expand-md.navbar-light.bg-light
    = link_to('/', title: "home", class: "navbar-brand") do
      %i.fas.fa-ad.fa-2x
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item{:class => current_page?(admin_users_path) && 'active'}
          = link_to 'Admin', admin_users_path, title: "Admin", class: "nav-link"


:javascript
  $(document).ready(function(){
    $('.dropdown-header').dropdown()
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title BesunshineClient
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      .text-center
        - flash.each do |key, value|
          = content_tag :div, class: "alert alert-#{key} alert-dismissible fade show", role: "alert" do
            = value
            %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
              %span{"aria-hidden" => "true"} ×
    = yield

app/views/welcome/index.html.haml
.container
  .text-center
    %h1 Besunshine Client

  .box
    .box-header.text-center
      %h3 Se connecter
    .box-body
      %br/
      = simple_form_for(:user, url: user_session_path) do |f|
        = f.label :email, "E-mail :"
        = f.input :email, required: false, label: false
        = f.label :password, "Mot de passe :"
        = f.input :password, required: false, label: false
        %br
        = f.button :submit, :class => "btn btn-success", :value => "Se connecter", :href => "/account"
      %br/
      .link
        = link_to "Mot de passe oublié?", new_password_path(:user), title: "Mot de passe oublié"